package co.edu.unicauca.mvc.vistas;

import co.edu.unicauca.mvc.accesoADatos.AutorRepositorio;
import co.edu.unicauca.mvc.accesoADatos.EvaluadorRepositorio;
import co.edu.unicauca.mvc.accesoADatos.OrganizadorRepositorio;
import co.edu.unicauca.mvc.controladores.ArticuloServices;
import co.edu.unicauca.mvc.controladores.AutorServicio;
import co.edu.unicauca.mvc.controladores.ConferenciaServices;
import co.edu.unicauca.mvc.controladores.EvaluadorServicio;
import co.edu.unicauca.mvc.controladores.OrganizadorServicio;
import co.edu.unicauca.mvc.vistas.adminConferencia.VtnPrincipalAdmin;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme;

import javax.swing.SwingUtilities;

/**
 * Clase VtnLogin que representa la ventana principal de login de la aplicación.
 * Hereda de javax.swing.JFrame para crear una interfaz gráfica que permite a los usuarios seleccionar
 * su rol y acceder al sistema correspondiente.
 * Se inicializan los servicios necesarios y se permite al usuario seleccionar entre los roles
 * disponibles: Organizador, Autor o Evaluador.
 */
public final class VtnLogin extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    private VtnPrincipalAdmin objVtnPrincipal;

    /**
     * Constructor de la clase que inicializa los componentes gráficos y los servicios necesarios.
     */
    public VtnLogin() {
        try {
            FlatMacDarkLaf.setup(); 
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }

        initComponents();
        inicializarResSer();
        SwingUtilities.updateComponentTreeUI(this);
    }

    /**
     * Método encargado de inicializar los repositorios y servicios de la aplicación.
     * Se asocian los servicios a la ventana principal del administrador.
     */
    public void inicializarResSer() {
        ConferenciaServices objSConferencia = new ConferenciaServices();

        ArticuloServices objSArticulo = new ArticuloServices();

        OrganizadorRepositorio objROrganizador = new OrganizadorRepositorio();
        OrganizadorServicio objSOrganizador
                = new OrganizadorServicio(objROrganizador);

        EvaluadorRepositorio objREvaluador = new EvaluadorRepositorio();
        EvaluadorServicio objSEvaluador = new EvaluadorServicio(objREvaluador);

        AutorRepositorio objRAutor = new AutorRepositorio();
        AutorServicio objSAutor = new AutorServicio(objRAutor);

        this.objVtnPrincipal = new VtnPrincipalAdmin();
        //objVtnPrincipal.asociarServios(objSConferencia, objSArticulo, 
                //objSOrganizador, objSEvaluador, objSAutor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        cmbRol = new javax.swing.JComboBox<>();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));

        cmbRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Rol", "Organizador", "Autor", "Evaluador" }));
        cmbRol.setToolTipText("");
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    /**
     * Método que maneja el evento de selección de rol en el comboBox.
     * Dependiendo del rol seleccionado, abre la ventana principal correspondiente.
     */
    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {                                       
        String opcion = (String) cmbRol.getSelectedItem();
        if (!opcion.equals("Seleccione Rol")) {
            objVtnPrincipal.gestionRol(opcion);
            objVtnPrincipal.setVisible(true);
        } else {
            lblResultado.setText("Seleccione un rol válido");
        }
    }                                      

    /**
     * Método principal que inicia la ejecución de la ventana de login.
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VtnLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration                   
}
