package co.edu.unicauca.mvc.vistas.evaluador;

import co.edu.unicauca.mvc.controladores.ArticuloServices;
import co.edu.unicauca.mvc.controladores.EvaluadorServicio;
import co.edu.unicauca.mvc.modelos.Articulo;
import co.edu.unicauca.mvc.modelos.Evaluador;
import co.edu.unicauca.mvc.modelos.Rol;
import co.edu.unicauca.mvc.modelos.Usuario;
import co.edu.unicauca.mvc.utilidades.Utilidades;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Mary
 */
/**
 * Clase VtnActualizarEvaluador.
 *
 * Esta clase representa una ventana (JFrame) para actualizar la información de
 * un evaluador en la aplicación. Proporciona la funcionalidad para cargar los
 * datos de un evaluador específico en la interfaz gráfica, permitiendo al
 * usuario modificar y guardar los cambios.
 */
public class VtnActualizarEvaluador extends javax.swing.JFrame {

    private ArticuloServices objSArticulo;
    private EvaluadorServicio objSEvaluador;

    /**
     * Constructor para crear la ventana de actualización de evaluadores
     *
     * @param objSArticulo Servicio de gestión de artículos
     * @param objSEvaluador Servicio de gestión de evaluadores
     */
    public VtnActualizarEvaluador(
            ArticuloServices objSArticulo,
            EvaluadorServicio objSEvaluador) {
        initComponents();
        this.objSArticulo = objSArticulo;
        this.objSEvaluador = objSEvaluador;
    }

    /**
     * Carga los datos del evaluador en los campos del formulario
     *
     * @param idEvaluador Identificador del evaluador a actualizar
     */
    public void cargarDatos(int idEvaluador) {
        Usuario usuario = objSEvaluador.consultarEvaluador(idEvaluador); // Obtener Usuario desde la API

        if (usuario != null) {
            txtIdAct.setText(String.valueOf(usuario.getId())); // ID no editable
            txtNomAct.setText(usuario.getNombre());
            txtApeAct.setText(usuario.getApellido());
            txtCorreoAct.setText(usuario.getCorreo());
            System.out.println("Datos cargados: " + usuario.getNombre() + ", " + usuario.getApellido() + ", " + usuario.getCorreo());
        } else {
            System.out.println("No se encontró un usuario con ID: " + idEvaluador);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelInferior = new javax.swing.JPanel();
        jButtonActualizar = new javax.swing.JButton();
        jPanelCentral = new javax.swing.JPanel();
        jLabelId = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtIdAct = new javax.swing.JTextField();
        txtNomAct = new javax.swing.JTextField();
        txtApeAct = new javax.swing.JTextField();
        txtCorreoAct = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setText("Actualizar Evaluador");

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

        jPanelInferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonActualizar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButtonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/comunicacion.png"))); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInferiorLayout = new javax.swing.GroupLayout(jPanelInferior);
        jPanelInferior.setLayout(jPanelInferiorLayout);
        jPanelInferiorLayout.setHorizontalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInferiorLayout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(jButtonActualizar)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelInferiorLayout.setVerticalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonActualizar)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelInferior, java.awt.BorderLayout.PAGE_END);

        jPanelCentral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelId.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelId.setText("Id:");

        jLabelNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelApellido.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelApellido.setText("Apellido:");

        lblCorreo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblCorreo.setText("Temas Experto: ");

        txtIdAct.setEditable(false);

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelApellido)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelId)
                    .addComponent(lblCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtApeAct, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(txtNomAct)
                    .addComponent(txtIdAct, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoAct, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelId)
                    .addComponent(txtIdAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombre)
                    .addComponent(txtNomAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido)
                    .addComponent(txtApeAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreoAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        int id = Integer.parseInt(txtIdAct.getText());
        String nombre = txtNomAct.getText();
        String apellido = txtApeAct.getText();
        String correo = txtCorreoAct.getText();

        // Crear objeto Rol para el evaluador
        Rol rolEvaluador = new Rol(); // Asegúrate de que Rol tenga un constructor adecuado
        rolEvaluador.setId(2); // Asumiendo que el ID para "EVALUADOR" es 2
        rolEvaluador.setNombre("EVALUADOR");

        // Crear objeto Usuario con los nuevos datos
        Usuario usuarioActualizado = new Usuario(
                id, // Asegúrate de que este ID es correcto
                nombre,
                apellido,
                correo,
                rolEvaluador // Asignar el rol "EVALUADOR"
        );

        // Llamar al servicio para actualizar el evaluador (Usuario en la API)
        boolean actualizado = objSEvaluador.actualizarEvaluador(usuarioActualizado);

        if (actualizado) {
            JOptionPane.showMessageDialog(this, "Evaluador actualizado exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el evaluador.");
        }
    }//GEN-LAST:event_jButtonActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelInferior;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JTextField txtApeAct;
    private javax.swing.JTextField txtCorreoAct;
    private javax.swing.JTextField txtIdAct;
    private javax.swing.JTextField txtNomAct;
    // End of variables declaration//GEN-END:variables
}
