package co.edu.unicauca.mvc.vistas.adminConferencia;

import co.edu.unicauca.mvc.controladores.ConferenciaServices;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import co.edu.unicauca.mvc.modelos.Conferencia;
import java.text.ParseException;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JTable;

/**
 * Clase que representa una ventana interna para listar conferencias.
 * Permite registrar y mostrar conferencias en una tabla.
 */
public class VtnListarConferencias extends javax.swing.JInternalFrame {
    /**
     * Servicio de almacenamiento de conferencias.
     */
    private ConferenciaServices objServicioAlmacenamiento;
    /**
     * Constructor de la clase. Inicializa los componentes y carga los datos de conferencias.
     *
     * @param objServicioAlmacenamiento Servicio de almacenamiento de conferencias.
     */
    
    public VtnListarConferencias(ConferenciaServices objServicioAlmacenamiento) {
        initComponents();
        this.objServicioAlmacenamiento = objServicioAlmacenamiento;
        //agregaDatos();
        llenarTabla();
    }


    
    /**
     * Gestiona la visibilidad de los elementos de la ventana según el rol del usuario.
     *
     * @param rol El rol del usuario (Autor, Evaluador, Organizador).
     */

    public void gestionRol(String rol) {
        switch (rol) {
            case "AUTOR":
                jButtonRegistrar.setVisible(false);
                break;
            case "ORGANIZADOR":
                jButtonRegistrar.setVisible(true);
                break;
            default:
                break;
        }
    }
    /**
     * Limpia todas las filas de la tabla de conferencias.
     */
    public void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTableListadoConferencias.getModel();
        int filas = this.jTableListadoConferencias.getRowCount();
        for (int i = 0; filas > i; i++) {
            modelo.removeRow(0);
        }
    }
    
    /**
     * Llena la tabla de conferencias con los datos almacenados.
     */

    public void llenarTabla() {
        DefaultTableModel model = (DefaultTableModel) this.jTableListadoConferencias.getModel();
        limpiarTabla();
        ArrayList<Conferencia> listaConferencias = (ArrayList<Conferencia>) this.objServicioAlmacenamiento.listarConferencias();
        //SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

        for (int i = 0; i < listaConferencias.size(); i++) {
            String[] fila = {
                listaConferencias.get(i).getNombre(),
                listaConferencias.get(i).getFechaInicio(),
                listaConferencias.get(i).getFechaFin(),
                listaConferencias.get(i).getUbicacion()
            };
            model.addRow(fila);
        }

    }

    public JTable getjTableListadoConferencias() {
        return jTableListadoConferencias;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInferior = new javax.swing.JPanel();
        jPanelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListadoConferencias = new javax.swing.JTable();
        jButtonRegistrar = new javax.swing.JButton();
        jPanelSuperior = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanelInferior.setPreferredSize(new java.awt.Dimension(198, 30));

        javax.swing.GroupLayout jPanelInferiorLayout = new javax.swing.GroupLayout(jPanelInferior);
        jPanelInferior.setLayout(jPanelInferiorLayout);
        jPanelInferiorLayout.setHorizontalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        jPanelInferiorLayout.setVerticalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelInferior, java.awt.BorderLayout.SOUTH);

        jTableListadoConferencias.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jTableListadoConferencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "FECHA INICIO", "FECHA FIN", "UBICACION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListadoConferencias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableListadoConferencias.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(jTableListadoConferencias);

        jButtonRegistrar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/agregar.png"))); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrar)))
                .addContainerGap())
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        jPanelSuperior.setPreferredSize(new java.awt.Dimension(777, 30));

        jLabelTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Listado de conferencias");

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addContainerGap())
        );

        getContentPane().add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        VtnRegistrarConferencia objVtnRegistrarConferencia
        = new VtnRegistrarConferencia(this.objServicioAlmacenamiento, this);
        objVtnRegistrarConferencia.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        objVtnRegistrarConferencia.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelInferior;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListadoConferencias;
    // End of variables declaration//GEN-END:variables
}
